### ISSUE TITLE
ChQiita ブランチの取り扱い（マージ先）について

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/ChQiita#3]
## 確認

先ほど、PR をマージしたのですが、どうやら ChQiita の `master` にマージされてしまったようです。
（マージ時、`Qithub-ChQiita`ブランチになってた+`master`はロックをかけていた気がするのですが、、、）

修正前に、念のためブランチの取り扱いの確認をしたいと思います。

### 基本ブランチ

下記のように、本家に間違えて Push しないように `master` にコミットせず、`Qithub-ChQiita` ブランチに（ `master` 代わりにして）コミット・PR・マージして行くのが良いと思うのですが、いかがでしょう？ それとも `master` がわかりやすくてよいかしら？

- `master` → 本家とまったく同じクローン（フォーク）の**変更なし**ブランチ
- `Qithub-ChQiita` → 当リポジトリのメイン・ブランチで、**ChQiita 本体**。
- その他 → 従来と同様、マージされたら削除されるブランチ

----

## TL;DR（結論 2018/01/04）

- [本家](https://github.com/increments/kobito-oss)には PR しない（本家とは機能の趣旨が違うため）
- リリース用と開発用でリポジトリを分ける（ブランチで分けない。ポカよけのため）
    - リリース用リポジトリ： [`Qithub-BOT/ChQiita`](https://github.com/Qithub-BOT/ChQiita)
    - 開発用リポジトリ： [`Qithub-BOT/ChQiita-Dev`](https://github.com/Qithub-BOT/ChQiita-Dev)
- 各自の改造・改善 PR は `Qithub-BOT/ChQiita-Dev` で行う
- リリースは[プログラムチーム](https://github.com/orgs/Qithub-BOT/teams)が `ChQiita-Dev`→`ChQiita`にマージを行う
- `ChQiita` アプリの issue は `ChQiita-Dev` リポジトリ側で行う

**Comment by hidao80** [comment]
本家に間違えてコミット、当方の冬休みの宿題 ( https://hidao80.github.io/textlintereditor/ ) でもやらかしました。😓 要注意です。

## 対案A

- `Kobito-OSS/master` → 本家の最新動作可能版。**ここにはマージしない。**
- `Qithub-BOT/ChQiita/master` → `ChQiita` の最新動作検証済み版。我々はここにマージする。fork されるときはここからどうぞ。
- `Qithub-BOT/ChQiita/dev` → `ChQiita` の最新コミットブランチのルート。結合テスト用ブランチ。**ベータ版 or アルファ版で、fork 非推奨。**
- その他 → 従来と同様、マージされたら削除されるブランチ

としておいて、github.com の機能にある `Setting`→`Branches`→`Default Branch` を `dev` にしてはどうでしょう？ github.com 上での操作をしたとき、デフォルトのマージ先が `Qithub-BOT/ChQiita/dev` になるはずです。
初回のみ本家リポジトリ向きですが、上記設定後一度 PR 作成画面でローカルリポジトリ(=`Qithub-BOT/ChQiita`) を選択すれば次からは PR のデフォルトリポジトリがローカルリポジトリになるはずです。

また、オリジナルから変更なしの状態を独立したブランチは **`inital` などのリリース版とは関係ないことがわかる固有名詞で保管するのが良い**のではないかと考えます。
しかしこれも、fork 時点へのロールバックを簡単にするためだけのものです。単にロールバックするだけなら `git reset --hard HEAD~n` でロールバックできるので。

**Comment by KEINOS** [comment]
> github.com 上での操作をしたとき、デフォルトのマージ先が Qithub-BOT/ChQiita/dev になるはずです。

実は、すでに現在 `Setting` → `Branches` → `Default Branch` は `Qithub-ChQiita` （つまり `Qithub-BOT/ChQiita/Qithub-ChQiita`ブランチ）になっているんですが、なぜか`Qithub-BOT/ChQiita/master` にマージされてしまったようなので、要検証ですね。

## 対案 B（ポカよけ）

     `ChQiita/master` のブランチ名を `ChQiita/ChQiita-master`に変える

`master`が、本家の`Kobito-OSS/master`か`ChQiita/master`かの違いでポカをしそうです。

最初は `ChQiita/Qithub-ChQiita` ブランチを我々のマスター扱いにするのが良いかなとも思ったのですが、やはり`master`は`master`であるべきかなとも思います。

どうやら `master` ブランチの名前も変えられるようなので `master` → `ChQiita-master` に名前を変えて & それをデフォルト・ブランチに設定して、そこ（`ChQiita/ChQiita-master`）にマージしていくのはどうでしょう？

あとは従来通りでも良い気がします。

**Comment by hidao80** [comment]
### マージ時のポカよけ案C

今更感が半端ないですが、ポカよけという意味では面倒ですが、

1. `increments/kobito-oss` をローカルに clone。この時点で push の参照先がローカルに移る。
1. `Qithub-BOT/ChQiita` に push。push の参照先は自分自身 (`Qithub-BOT/ChQiita`) のまま。
1. 通常営業開始。

github の**fork 元に PR しようとする仕様**は git コマンドをかますことで回避できそうです。 

github リポジトリ作り直し or 上書きが必要ですが… 😓

**Comment by KEINOS** [comment]
確かにローカルを Push して Fork のリンクを切っちゃえば確実なポカよけなんですが、本家から派生したという GitHub のシステム的なつながりとして Fork しておきたいんですよね。

というのも Kobito 終了で (´；ω；`)ｼｮﾝﾎﾞﾘ したユーザーが Kobito-OSS を知って、（使ってもらえるかは別として）各々生きていると知ってもらえるだけでも、フォークの価値があると思うんですよね。

<kbd><img width="100%" alt="2018-01-02 23 06 47" src="https://user-images.githubusercontent.com/11840938/34486157-b25d51c2-f011-11e7-8aed-676c6bf13e80.png"></kbd>

ただ、Fork した状態で `master` を `ChQiita-master` にブランチ名を変更することで、かえって弊害があるなら検討したいです。

### 案B'

1. `Qithub-ChQiita` ブランチの削除
2. `master` → `master-ChQiita` にリネーム → 以後ここにマージ
3. 通常営業開始

**Comment by hidao80** [comment]
👍

押忍！ ChQiita 師匠について行きます！😁

**Comment by KEINOS** [comment]
### 作業報告

`master` ブランチ名を `master-ChQiita` に変更しました。

### 原因報告

先のマージした時に `master` にマージされた理由がわかりました。以下の２点が原因でした。

1. ``Qithub-BOT/ChQiita` **REPOの作成者が私（@KEINOS）だった**
2. `Qithub-BOT/ChQiita` REPO を**直接ローカルにクローン**した

つまり、コミットして Sync すると `Qithub/BOT/ChQiita` を直接触ったのと同じことでした。

そのため、他のユーザーでは発生しないとは思うのですが PR しようとすると以下のようなポカが発生しそうでした。

<kbd><img width="245" alt="2018-01-03 1 51 12" src="https://user-images.githubusercontent.com/11840938/34494005-bec47a38-f031-11e7-9a2e-ff4bc8c5fb66.png"></kbd>

そこで、これを踏まえて以下のようにしたいと思いますが、分かりづらいでしょうか？

<kbd>![chqiita](https://user-images.githubusercontent.com/11840938/34493785-c2a903b8-f030-11e7-9bcc-f2ec39f1baf5.png)</kbd>

**Comment by hidao80** [comment]
なるほど！ github は fork するとその親に PR する仕様なので、逆手にとって「孫 fork」を作る寸法ですね。妙案です。😮

しかしこれだと、**User A の成果を User B が受けるためには User A が 2 段階 push (push -> PR) して、User B が 2 段階 pull (fetch & merge × 2) が必要になって繁雑にすぎるかと思われます。**

## 対案 D

孫 fork を作成に 👍

**開発中はプロジェクトメンバ全員で一つの孫 fork (`Qithub-BOT/ChQiita-dev/master` (仮名)) に PR し、リリース版は `Qithub-BOT/ChQiita/master` に PR する**という運用でどうでしょう？

![図D: PR シーケンス](https://user-images.githubusercontent.com/8155294/34502067-2dea6940-f055-11e7-912d-6658e58e9496.jpeg)


これなら**Kobito 直系の子孫の動作可能最新版をリリース & fork しているアピールしつつ、PR 事故を防げ、さらに開発 REPO を一本化できると思う**のですが。

ご意見お待ちしてい 💪

P.S.
上記シーケンス図は「StackEdit」という Web Markdown Editor の `sequence` コードブロックを使って描いたものです。`flow` コードブロックもあるみたいです。便利！

**Comment by KEINOS** [comment]
なるほど、各自の GitHub アカウントへのフォークのかわりに自身（Qithub）でフォークすれば、PR先のポカは限りなく減りそうですね。 👍 

1. メンバーの PR 先は `ChQiita-dev` に行う
1. `ChQiita-DEV` → `ChQiita` へのリリース（PR）は、プログラムチームが on the Web で行う

issue の取り扱いはどうしましょう？ 

3. ここ（`ChQiita` Repo）の issue を閉鎖（ロック）して `ChQiita-dev` のみにする
4. `ChQiita` Repo の issue は仕様決め用にして `ChQiita-dev` の issue は不具合用にする
5. `ChQiita` Repo の issue はエンドユーザ用にして `ChQiita-dev` は開発者用にする

> StackEdit

おぉ、これは面白い。いいですね！
Googleの図形描画で書いてましたがレイアウトの微調整が必要なので、markdown でかけるのは良い 👍 

`scripts/` Repo の概要図もこれで描いてみようと思います。

**Comment by hidao80** [comment]
> 1. メンバーの PR 先は ChQiita-dev Repo に行う
>1. ChQiita-DEV → ChQiita Repo へのリリース（PR）は、プログラムチームが on the Web で行う

👌👍

issue は 3. の「ChQiita-devのみで行う」に👍
Issue が分散すると、見落としからの UX 低下、ひいては ChQiita の信用低下につながりかねないと考えます。開発に興味・要望がある方はdev に集まってもらうようにしましょう。
あくまで ChQiita REPO は「Kobito 伝承者であることの証明」と位置付けるのが良いのではないかと考えます。

**Comment by KEINOS** [comment]
### Forked リポジトリは同一アカウント内で再 Fork できない

`Qithub-BOT/ChQiita` リポジトリを Fork して `Qithub-BOT/ChQiita-Dev` を作ろうと思ったのですが、選択肢に `Qithub-BOT` が出て来ず **`fork` できませんでした**。

increments からの初回 Fork では Fork 先に `Qithub-BOT` が出て来たので `Qithub-BOT/Kobito-oss` を作成し `Qithub-BOT/ChQiita` にリネームできたのですが、同一アカウント内で Fork を再 Fork できないのはどうやら仕様らしく [`clone` & `push` しかないらしい](https://stackoverflow.com/a/10966784/8367711)です。

そこで、GitHub に `importer` という機能があっって既存リポジトリをインポート（Clone&Push）してくれるそうなので[やってみました](https://github.com/Qithub-BOT/ChQiita-Dev)。

#### How
<kbd><img width="100%" alt="2018-01-04 13 12 39" src="https://user-images.githubusercontent.com/11840938/34550259-b3733bc0-f152-11e7-923c-46a9c035ef47.png"></kbd>

#### Result
<kbd><img width="100%" alt="2018-01-04 13 32 21" src="https://user-images.githubusercontent.com/11840938/34550390-e38c9b5c-f153-11e7-889f-67c9065151ec.png"></kbd>

ご確認いただき、特に問題ないようであれば本 issue はクローズでお願いします。

クローズ後は、本リポジトリ（`Qithub-BOT/ChQiita`）の issue 機能はオフにして、以後は [`Qithub-BOT/ChQiita-Dev`](https://github.com/Qithub-BOT/ChQiita-Dev) 側で issue や PR を行いたいと思います。

**Comment by hidao80** [comment]
👌👍

ありがとうございます！😄
