### ISSUE TITLE
ラベル の設定

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/ChQiita#4]
## 報告

ChQiita リポジトリのラベルの色設定を [Qithubに準拠](https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md#-%E3%83%A9%E3%83%99%E3%83%AB) させました。

https://github.com/Qithub-BOT/ChQiita/labels

問題なければ Close 願います。

**Comment by hidao80** [comment]
👍
