### ISSUE TITLE
Kobito-OSS の仕様・ドキュメント・情報一覧

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/ChQiita#5]
Kobito-OSS をベースに ChQiita を作っていくにあたって、Electron 含め諸情報を TL;DR にリストアップして行きたいと思います。

## TL;DR

- [本 issue の運用方針（仮）](https://github.com/Qithub-BOT/ChQiita/issues/5#issuecomment-354728447)

### Kobito OSS 関連

- [Kobito-OSS （本家）のリポジトリ @ GitHub](https://github.com/increments/kobito-oss)
- [kobito-oss のソースの読み方 @ Qiita](https://qiita.com/mizchi/items/8b676d598325cedaa3f2)

### Electron 関連

- [Electronのリビルド手順](#issuecomment-354747117)

**Comment by hidao80** [comment]
TL;DR にヘッドラインを作り、本 issue に投稿された詳細情報へのリンクを貼るというのはどうでしょう?

コメントに対してリンクが貼れるようになっているいま、本 issue をドキュメントページとして良さそうだと考えています。

コメントに対して編集も行えるので、**Wiki のようで Wiki でない**使い方もありなのではないでしょうか。

情報収集が終わった後は、issue を close する事で後片付けもでき、検索で掘り出すこともできる優れものだと考えているのですが。

ご意見お待ちしてい💪

**Comment by KEINOS** [comment]
> TL;DR にヘッドラインを作り、本 issue に投稿された詳細情報へのリンクを貼る

[`items`リポジトリのスーパー皮算用 issue](https://github.com/Qithub-BOT/items/issues/14)みたいな管理方法ですね。いいと思います！ 👍

**Comment by KEINOS** [comment]
### Electron のリビルド手順

どうも [README.md](https://github.com/Qithub-BOT/ChQiita/blob/Qithub-ChQiita/README.md) を読んでいると、OSS版はWin用をベースにしているのでMac版と違うようなので、Macでリビルド（再構築）してみて、そもそも Mac で動くかを検証したいと思います。

### 参考リンク

- 【検索中】??? (　`･ω)(`･ω･)(｀･ω･´)(･ω･｀)(ω･｀ ) ???

**Comment by KEINOS** [comment]
#3 にともない、本リポジトリの issue 機能は 2018/01/04 20:00 に閉鎖するので、本 issue はクローズして `ChQiita-Dev` の issue （ Qithub-BOT/ChQiita-Dev/issues/2 ）へ移行します。
